@baseUrl = http://localhost:3333
[

]
### Listar usuários
GET {{baseUrl}}/users

### Buscar usuário por id
GET {{baseUrl}}/users/1

### Atualizar usuário
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
  "name": "John Updated",
  "password": "Demo@123456",
  "confirmPassword": "Demo@123456"
}

### Remover usuário
DELETE {{baseUrl}}/users/1
