@baseUrl = http://localhost:3333
[

]
### Buscar o proprio usuario autenticado
GET {{baseUrl}}/users/me

### Atualizar o proprio usuario autenticado
PATCH {{baseUrl}}/users/me
Content-Type: application/json

{
  "name": "John Updated",
  "password": "Demo@123456",
  "confirmPassword": "Demo@123456"
}

### Remover o proprio usuario autenticado
DELETE {{baseUrl}}/users/me
